export default function getArchiveList() {
  return [
    {
      year: '2024',
      name: 'Gitly',
      madeAt: 'Github',
      built: 'Apollo Client, IOS App, SwiftUI, GraphQL, Pagination, Nested Push Navigations',
      isOpenSource: true,
    },{
      year: '2023',
      name: 'Link Loom',
      madeAt: 'Github',
      built: 'Chromecast SDK, Android Tv App, Jetpack Compose Android Tv SDK, Chromecast Push Events',
      isOpenSource: true,
    },{
      year: '2023',
      name: 'Rick And Morty IOS App',
      madeAt: 'Github',
      built: 'UIKit, Swift, IOS App, Alamofire, RealmSwift, CollectionView, Permissions, Localizations',
      isOpenSource: true,
    },{
      year: '2023',
      name: 'Karkdown Compose',
      madeAt: 'Github',
      built: 'Jetpack Compose, Maven Central',
      isOpenSource: true,
    },
    {
      year: '2023',
      name: 'KMM Sopy',
      madeAt: 'Github',
      built: 'Kotlin Multiplatform Mobile, IOS, Android, Maven Central',
      isOpenSource: true,
    },{
      year: '2023',
      name: 'Compare Url',
      madeAt: 'Github',
      built: 'Macos App, SwiftUI',
      isOpenSource: true,
    },
    {
      year: '2023',
      name: 'Coina',
      madeAt: 'Github',
      built: 'Kotlin Multiplatform Mobile, IOS App, Android App, Jetpack Compose, SwiftUI, MVVM, Ktor Client',
      isOpenSource: true,
    },
    {
      year: '2022',
      name: 'Avalugg',
      madeAt: 'Github',
      built: 'Swift, XCode IDE, Macos Application, ADB, Shell Commands',
      isOpenSource: true,
    },
    {
      year: '2022',
      name: 'Zeeva',
      madeAt: 'Github',
      built: 'Ruby, Fastlane, Gem',
      isOpenSource: true,
    },
    {
      year: '2022',
      name: 'Mushrrom',
      madeAt: 'Github',
      built: 'Typescript, Nest.js, Discord Bot, Google Maven Api, Github Api V3, Cron Job',
      isOpenSource: true,
    },
    {
      year: '2021',
      name: 'Legora',
      madeAt: 'Github',
      built: 'Riot Api, Gson, Retrofit, Coroutines, Vanite, ViewBinding, Multi Modular App, Deeplinks',
      isOpenSource: false,
    },
    {
      year: '2021',
      name: 'Zilon',
      madeAt: 'Github',
      built: 'Typescript, Nest.js, Slack Api, Google Maven Api, Github Api V3, Cron Job',
      isOpenSource: true,
    },
    {
      year: '2021',
      name: 'Viper Idea',
      madeAt: 'Github',
      built: 'Android Studio Plugin, Intellij Plugin, Kotlin, Gradle Api, Arctic Fox, Fragments, RecyclerViews',
      isOpenSource: true,
    },
    {
      year: '2021',
      name: 'Shake Reporter',
      madeAt: 'Github',
      built: 'AppCompat (AndroidX), Kotlin, OkHttp, Retrofit, Crashes, Shake Sensor, Fragments, Activity Aliases',
      isOpenSource: true,
    },
    {
      year: '2021',
      name: 'Palex Adapter',
      madeAt: 'Github',
      built: 'AppCompat (AndroidX), Kotlin, RecyclerViews, MultiView Holder, SingleViewHolder',
      isOpenSource: true,
    },
    {
      year: '2021',
      name: 'Issuer Kt',
      madeAt: 'Github',
      built: 'AppCompat (AndroidX), Fragments, Kotlin, Attach Images, Device Information, Material Design',
      isOpenSource: true,
    },
    {
      year: '2021',
      name: 'Cloner Js',
      madeAt: 'Github',
      built: 'CLI, JavaScript, Github Api V3, Files Library, Json Configuration',
      isOpenSource: true,
    },
    {
      year: '2021',
      name: 'Portfolio',
      madeAt: 'Github',
      built: 'Domain, CDN, React.js, React Hooks, SASS, Material UI, Github Pages, JavaScript ES6+, PWA',
      isOpenSource: true,
    },
    {
      year: '2021',
      name: 'Android Template Kt',
      madeAt: 'Github',
      built: 'Gradle DSL, Gradle Kotlin Configuration, AndroidX Libraries, Gradle Files Structure, BuildSrc',
      isOpenSource: true,
    },
    {
      year: '2021',
      name: 'Portfolio Next',
      madeAt: 'Github',
      built: 'React.js, React Hooks, SASS, Material UI, Github Pages, JavaScript ES6+, Next.js',
      isOpenSource: true,
    },
    {
      year: '2021',
      name: 'Shop Api',
      madeAt: 'Github',
      built: 'PHP, Laravel, MySql, Table Migration, JWT Tokens, Routers',
      isOpenSource: true,
    },
    {
      year: '2021',
      name: 'Commiter',
      madeAt: 'Github',
      built: 'Ruby, Git Hooks, Messages Validation, CLI, Gem',
      isOpenSource: true,
    },
    {
      year: '2021',
      name: 'Github Clone',
      madeAt: 'Github',
      built: 'Desktop Design, Material UI, Github Api V3, React.js, React Hooks, React Bootstrap',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Denamo',
      madeAt: 'Github',
      built: 'VsCode Themes, VsCode Plugins, TypeScript, Json Configuration',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Netflix Clone',
      madeAt: 'Github',
      built: 'Desktop Design, Material UI, Github Api V3, React.js, React Hooks, React Bootstrap, Firebase Hosting',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Vortex Gradle Plugins',
      madeAt: 'Github',
      built: 'Groovy, Gradle Plugins, Android Plugins, Multi Modular Apps Plugins',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Groupy',
      madeAt: 'Github',
      built: 'Firebase, Firestore, Realtime Chat Database, Firebase Auth, MVP, AndroidX, Kotlin',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Feature Flag Example',
      madeAt: 'Github',
      built: 'Kotlin, Spring Boot, Rest Api',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Github Client',
      madeAt: 'Github',
      built: 'Vortex, Navigation Components, Kotlin, Androidx, Retrofit, Github Api V3',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Exposer',
      madeAt: 'Github',
      built: 'Kotlin Multi Platform, Domain Layer, RxJava, Kotlin Coroutines',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Actor',
      madeAt: 'Github',
      built: 'Postman Collections, SpringBoot, Json Parser',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Ktor Example',
      madeAt: 'Github',
      built: 'Ktor Framework, Netty Engine, Restful Api, Kotlin Extensions',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Destiny Api',
      madeAt: 'Github',
      built: 'Spring Boot, Kotlin, MySql, Firebase Admin SDK, JWT Security, Spring JPA',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Destiny App',
      madeAt: 'Github',
      built: 'Vortex, AndroidX, Multi Modular Application, Kotlin, Kotlin Coroutines',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Thentrom',
      madeAt: 'Github',
      built: 'Intellij Theme, Intellij Plugin, Jar Files Build',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Wintrop',
      madeAt: 'Github',
      built: 'Vortex, Kotlin, Fragments, Redux, MVVM, Retrofit, OkHttp, Kotlin Coroutines, Open Weather Api',
      isOpenSource: true,
    },
    {
      year: '2020',
      name: 'Drasati',
      madeAt: '_',
      built: 'MVP, Kotlin, Firebase, Firebase Auth, Firestore, Realtime Chat',
      isOpenSource: false,
    },
    {
      year: '2019',
      name: 'Vortex',
      madeAt: 'Github',
      built: 'Firebase, Kotlin, MVVM, Redux, AndroidX, Multi Modules, Loggers, UI Utils, Bintray, RxJava',
      isOpenSource: true,
    },
    {
      year: '2019',
      name: 'Atto',
      madeAt: 'Github',
      built: 'MVP, Kotlin, Deprecated, Base Code, Multi Modules, Bintray, RxJava',
      isOpenSource: true,
    },
  ];
}
