// eslint-disable-next-line import/prefer-default-export
export function getProfileInfo() {
  return {
    Name: 'Yazan Tarifi',
    SmallDescription: 'Android Developer',
    Description: 'A code-minded front-end software engineer focused on building beautiful interfaces & experiences and Convert Ideas, Design To System With Frontend Side (Android Apps, React Websites, Next.js Websites) also The Backend Side With (SpringBoot, Ktor, Nest.js, Laravel), Always Trying To Build Tools To Help and Improve My Work',
    SkillsList: [
      'Android Apps',
      'Restful Api',
      'Websites',
    ],
  };
}

export function getProjectsList() {
  return [
    {
      type: 'android',
      name: 'Autohub',
      typeText: 'Android Application - Open Source',
      description: 'An Github Client Built To Test Vortex Infrastructure For Android Applications With A Lot Of Features To Manage Github Accounts Personal Accounts, Repositories, Search Repository, Popular Repos, Orgs, Gists, Github Auth, With Kotlin Programming Language',
      link: 'https://github.com/Yazan98/Github-Client',
      createdAt: 'Github - 2019',
      mainImage: '/autohub.webp',
      previewImage: '/autohub_preview.webp',
      images: [
        '/autohub_1.webp',
        '/autohub_2.webp',
        '/autohub_3.webp',
        '/autohub_4.webp',
      ],
      tags: [
        'MVVM',
        'Vortex',
        'Kotlin',
        'Retrofit',
        'RxJava',
        'Kotlin Courotines',
        'Multi Modular App',
      ],
    },
    {
      type: 'android',
      name: 'Drasati',
      typeText: 'Android Application - Closed Source',
      description: 'An organizing platform for school students that aims to gather students and link them with audible lessons by providing a tree plan with the possibility to speak with teachers if a difference occurs on a certain point with the support feature of all classes',
      link: '',
      createdAt: '2018',
      mainImage: '/drasati_main.webp',
      previewImage: '/drasati_preview.webp',
      images: [
        '/drasati_1.webp',
        '/drasati_2.webp',
        '/drasati_3.webp',
      ],
      tags: [
        'MVVM',
        'Vortex',
        'Kotlin',
        'Retrofit',
        'RxJava',
        'Kotlin Courotines',
        'Multi Modular App',
      ],
    },
    {
      type: 'android',
      name: 'Wintrop',
      typeText: 'Android Application - Open Source',
      description: 'Weather Application Powered By Vortex , Latest Android Technologies With Managed Structure To Show Weather Status For Amman, Irbid, Aqaba',
      link: 'https://github.com/Yazan98/Wintrop',
      createdAt: '2019',
      mainImage: '/wintrop_main.webp',
      previewImage: '/wintrop_preview.webp',
      images: [
        '/wintrop_1.webp',
        '/wintrop_2.webp',
        '/wintrop_3.webp',
      ],
      tags: [
        'MVVM',
        'Vortex',
        'Kotlin',
        'Retrofit',
        'RxJava',
        'Kotlin Courotines',
        'Multi Modular App',
      ],
    },
    {
      type: 'android',
      name: 'Destiny',
      typeText: 'Android Application - Open Source',
      description: 'Restaurant Application Powered By Vortex Infrastructure With Latest Technologies, Realm Database, Restful Api, Trainig Project and Testing For Vortex Testing',
      link: 'https://github.com/Yazan98/Destiny',
      createdAt: 'Github - 2019',
      mainImage: '',
      previewImage: '/destiny_preview.webp',
      images: [],
      tags: [
        'MVVM',
        'Vortex',
        'Kotlin',
        'Retrofit',
        'RxJava',
        'Kotlin Courotines',
        'Multi Modular App',
      ],
    },
    {
      type: 'android',
      name: 'Vortex',
      typeText: 'Android Library - Open Source',
      description: 'Restaurant Application Powered By Vortex Infrastructure With Latest Technologies, Realm Database, Restful Api, Trainig Project and Testing For Vortex Testing',
      link: 'https://github.com/Yazan98/Vortex',
      createdAt: 'Github - 2019',
      mainImage: '',
      previewImage: '/vortex_preview.webp',
      images: [],
      tags: [
        'MVVM',
        'Vortex',
        'Kotlin',
        'Retrofit',
        'RxJava',
        'Kotlin Courotines',
        'Multi Modular App',
      ],
    },
    {
      type: 'android',
      name: 'Vortex',
      typeText: 'Android Library - Closed Source',
      description: 'Restaurant Application Powered By Vortex Infrastructure With Latest Technologies, Realm Database, Restful Api, Trainig Project and Testing For Vortex Testing',
      link: 'https://github.com/Yazan98/Vortex',
      createdAt: ' 2019',
      mainImage: '',
      previewImage: '/mwarrid_preview.webp',
      images: [],
      tags: [],
    },
    {
      type: 'web',
      name: 'Portfolio',
      typeText: 'Website (React.js) - Open Source',
      description: 'My Personal Portfolio Built In React.js SPA, PWA',
      link: 'https://github.com/Yazan98/portfolio',
      createdAt: '2020',
      mainImage: '/portfolio_main.webp',
      previewImage: '/portfolio_preview.webp',
      images: [
        '/wintrop_1.webp',
        '/wintrop_2.webp',
        '/wintrop_3.webp',
      ],
      tags: [
        'MVVM',
        'Vortex',
        'Kotlin',
        'Retrofit',
        'RxJava',
        'Kotlin Courotines',
        'Multi Modular App',
      ],
    },
    {
      type: 'web',
      name: 'Portfolio V2',
      typeText: 'Website (Next.js) - Open Source',
      description: 'My Personal Portfolio Built In React.js SPA, PWA',
      link: 'https://github.com/Yazan98/portfolio-next',
      createdAt: '2020',
      mainImage: '/portfolio_main.webp',
      previewImage: '/portfolio_preview.webp',
      images: [
        '/wintrop_1.webp',
        '/wintrop_2.webp',
        '/wintrop_3.webp',
      ],
      tags: [
        'MVVM',
        'Vortex',
        'Kotlin',
        'Retrofit',
        'RxJava',
        'Kotlin Courotines',
        'Multi Modular App',
      ],
    },
    {
      type: 'web',
      name: 'Netflix Clone',
      typeText: 'Website (React.js) - Open Source',
      description: 'Netflex Clone To Show Movies Based on MoviesDB Api And React Hooks',
      link: 'https://github.com/Yazan98/Netflix-Clone',
      createdAt: '2020',
      mainImage: '/portfolio_main.webp',
      previewImage: '/netflex_preview.webp',
      images: [
        '/wintrop_1.webp',
        '/wintrop_2.webp',
        '/wintrop_3.webp',
      ],
      tags: [
        'MVVM',
        'Vortex',
        'Kotlin',
        'Retrofit',
        'RxJava',
        'Kotlin Courotines',
        'Multi Modular App',
      ],
    },
    {
      type: 'web',
      name: 'Github Clone',
      typeText: 'Website (React.js) - Open Source',
      description: 'Github Api V3 Project To Show Popular Repos, PWA, Show Profile Repos, Information',
      link: 'https://github.com/Yazan98/github-clone',
      createdAt: '2020',
      mainImage: '/portfolio_main.webp',
      previewImage: '/github_preview.webp',
      images: [
        '/wintrop_1.webp',
        '/wintrop_2.webp',
        '/wintrop_3.webp',
      ],
      tags: [
        'MVVM',
        'Vortex',
        'Kotlin',
        'Retrofit',
        'RxJava',
        'Kotlin Courotines',
        'Multi Modular App',
      ],
    },
    {
      type: 'api',
      name: 'Shopie Api',
      typeText: 'Restful Api - Open Source',
      description: 'Github Api V3 Project To Show Popular Repos, PWA, Show Profile Repos, Information',
      link: 'https://github.com/Yazan98/shop-api',
      createdAt: '2021',
      mainImage: '/portfolio_main.webp',
      previewImage: '/shopie_preview.webp',
      images: [
        '/wintrop_1.webp',
        '/wintrop_2.webp',
        '/wintrop_3.webp',
      ],
      tags: [
        'MVVM',
        'Vortex',
        'Kotlin',
        'Retrofit',
        'RxJava',
        'Kotlin Courotines',
        'Multi Modular App',
      ],
    },
    {
      type: 'api',
      name: 'Destiny Api',
      typeText: 'Restful Api - Open Source',
      description: 'Github Api V3 Project To Show Popular Repos, PWA, Show Profile Repos, Information',
      link: 'https://github.com/Yazan98/shop-api',
      createdAt: '2019',
      mainImage: '/portfolio_main.webp',
      previewImage: '/destiny_api_preview.webp',
      images: [
        '/wintrop_1.webp',
        '/wintrop_2.webp',
        '/wintrop_3.webp',
      ],
      tags: [
        'MVVM',
        'Vortex',
        'Kotlin',
        'Retrofit',
        'RxJava',
        'Kotlin Courotines',
        'Multi Modular App',
      ],
    },
    {
      type: 'opensource',
      name: 'All Projects',
      typeText: 'View All Projects Open, Closed Source',
      description: 'Github Api V3 Project To Show Popular Repos, PWA, Show Profile Repos, Information',
      link: 'https://github.com/Yazan98/shop-api',
      createdAt: '2018 - Present',
      mainImage: '/portfolio_main.webp',
      previewImage: '/all_preview.webp',
      images: [],
      tags: [],
    },
  ];
}

export function getProjectsListByFilter(filter = 'all') {
  const apps = getProjectsList();
  const appsFiltered = [];
  for (let i = 0; i < apps.length; i++) {
    if (apps[i].type === filter) {
      appsFiltered.push(apps[i]);
    }
  }
  return appsFiltered;
}
